### ISSUE TITLE
Unable to resolve host "adservice.google.com" error

### ISSUE THREAD

**Issue by mbpictures** [googleads/googleads-consent-sdk-android#104]
Hi!

I added the example code from the docs to the onCreate Method in Java and the "onFailedToUpdateConsentInfo" listener gets called with an "Unable to resolve host "adservice.google.com" " error. Do you have an idea how to solve this?
I've added the INTERNET and READ_NETWORK_STATE permission. I'm using version 1.0.6.

Best regards!

**Comment by rareserban** [comment]
Untill more information is provided, can you please tell if you have ads
implemented as well?

**Comment by mbpictures** [comment]
Well... no, I haven't AdMob integrated yet, because I wanted to get the consent SDK working. Is the implementation of admob necessary in order to use the consent SDK?

**Comment by rareserban** [comment]
Well, consent actually about ads...

**Comment by mbpictures** [comment]
I solved it. I had several mistakes in my implementation:
1. I called "show" immediatly after "load" which caused an "Consent form was not ready to be displayed error"
2. I used the getApplication().getContext() method to instantiate the consent sdk. With "MainActivity.this", it works
