### ISSUE TITLE
ConsentForm issue

### ISSUE THREAD

**Issue by iordachiv** [googleads/googleads-consent-sdk-android#11]
Hello,
I run into strange issues using ConsentForm, when try to load  form I get: "Error: invalid data. Unexpected end of JSON input" and on show: "Consent form is not ready to be displayed." even if show is called after 2 seconds delay.
Also I noticed that ConsentInformation.getInstance(this).setDebugGeography(DebugGeography.DEBUG_GEOGRAPHY_EEA); has no effect because consentInformation.isRequestLocationInEeaOrUnknown() return false;
Last thing, onFailedToUpdateConsentInfo return: "Could not parse Event FE preflight response." and for me isn't clear that mean such error.
Thanks in advance.

**Comment by rampara** [comment]
@iordachiv are you experiencing this issue on the latest version of this SDK (v1.0.1) ?

**Comment by iordachiv** [comment]
Yes, this occur on the version 1.0.1, requestConsentInfoUpdate each time return :onFailedToUpdateConsentInfo->"Could not parse Event FE preflight response." and ConsentForm is not displayed. I don't know how is possible to use this sdk in production.

**Comment by rampara** [comment]
@iordachiv would you be able to capture and share a network log when you experience this issue?

**Comment by rampara** [comment]
@iordachiv also, if you're using proguard, can you follow the instructions in #22.

**Comment by wanghang199112** [comment]
@iordachiv 
Have you addTestDevice?
consentInformation.addTestDevice("xxxxxxx");

**Comment by iordachiv** [comment]
@rampara sorry, it was my fault, I set wrong publisherIds, now it's ok.
