### ISSUE TITLE
Permission "android.permission.READ_PHONE_STATE" added

### ISSUE THREAD

**Issue by giorgosneokleous93** [googleads/googleads-consent-sdk-android#13]
I've just tried the consent SDK and it seems that it adds

> android.permission.READ_PHONE_STATE

Is the permission needed? If yes, I am guessing that it will cause issues since almost all of the apps that uses the Admob SDK will have to include this permission if they don't have it already. Adding new permissions might cause users to not update or even uninstall the app.

Is this intentional or should we wait for a fix?

**Comment by rampara** [comment]
@giorgosneokleous93 this will be fixed in an upcoming release.

**Comment by hkbb2014** [comment]
When will you fix it? I have to update apps with consent sdk

**Comment by mkaflowski** [comment]
The reason is:
`reason: com.google.android.ads.consent has a targetSdkVersion < 4`
So I think it will be safe to remove it for now with:
`    <uses-permission android:name="android.permission.READ_PHONE_STATE" tools:node="remove" />`

**Comment by hkbb2014** [comment]
@mkaflowski  @dzungpv Is it save to remove WRITE_EXTERNAL_STORAGE?

**Comment by mkaflowski** [comment]
@hkbb2014 I don't know. I use it anyway. You can check in build/outputs/logs/manifest-merger-release-report.txt or debug one why it was added I think.

**Comment by rampara** [comment]
This should no longer be an issue on the latest version of this SDK (v1.0.2).

**Comment by amarilindra** [comment]
Quick fix: Add this in your manifest.xml 
`    <uses-permission tools:node="remove" android:name="android.permission.READ_PHONE_STATE"/>
`
