### ISSUE TITLE
What should i do when no internet? and no Paid version

### ISSUE THREAD

**Issue by MrAdr68** [googleads/googleads-consent-sdk-android#15]
- What should i do when user not have internet connection? Can not load consent form? While user using app, internet connection comeback? How to solve this problem and display Ads?
- I do not want to create paid version? can i close app when user not select NPA/ PA??
- Consent form alway show when launch app. It will give user bad experiences. Why SDK not save their choice and give a option to revoke if user want? Form show only one time.
- Please give us a sample, demo for SDK.

- Deadline to update app to play store?

**Comment by rampara** [comment]
@MrAdr68 you should check the user's consent status and only display the form when the user has an `UNKNOWN` consent status or wishes to update their consent status. The user's consent status is saved and read by the Consent SDK as described in the [developer docs](https://developers.google.com/admob/android/eu-consent#consent_sdk).

As for your other questions, this issue tracker is strictly for technical issues, feature requests and bug reports for this Consent SDK. For all other questions regarding the Consent SDK, I recommend reaching out on the [AdMob product support forum](https://productforums.google.com/forum/#!forum/google-admob-help-forum).
