### ISSUE TITLE
Select your preferred ad technology providers.

### ISSUE THREAD

**Issue by MrAdr68** [googleads/googleads-consent-sdk-android#17]
I only use Admob in application ( no mediation). What should i do? I saw about 200 providers, i do not know about them.
Which provider i need to select?

**Comment by matt1** [comment]
Likewise - I have selected 2 or 3 in the AdMob Web site, yet ConsentInformation.getInstance(getApplicationContext()).getAdProviders() is returning 200.

This means that I cannot display the consent form since that only allows 12.

**Comment by matt1** [comment]
Ok so it seems like this might just be a delay.  I checked again now and the getAdProviders() call is returning a list that matched what is in the UI now.

**Comment by rampara** [comment]
@matt1 changes made in your AdMob account settings can take up to an hour to propagate. 

@MrAdr68 this issue tracker is strictly for technical issues, feature requests and bug reports for this Consent SDK. For all other questions I recommend reaching out on the [AdMob product support forum](https://productforums.google.com/forum/#!forum/google-admob-help-forum).
