### ISSUE TITLE
exaple text

### ISSUE THREAD

**Issue by michalbukacek** [googleads/googleads-consent-sdk-android#18]
you have an example of text with personal data protection to page privacyUrl.
everything that happens with the data is through the SDK component Admob. I do not know anything about users.

**Comment by rampara** [comment]
@michalbukacek this issue tracker is strictly for technical issues, feature requests and bug reports for this Consent SDK. For all other questions I recommend reaching out on the [AdMob product support forum](https://productforums.google.com/forum/#!forum/google-admob-help-forum).
