### ISSUE TITLE
[No thanks] button on ConsentForm

### ISSUE THREAD

**Issue by kanitawa** [googleads/googleads-consent-sdk-android#21]
My app has no "ads-free" version, only "ads" version.
So, I want to quit my app when user did not consent "see ads that are less relevant".

Current version of this SDK, only
 [Yes, contiinue to see relevant ads]
 [No, see ads that are less lerevant]
 [Pay for the ads-free version]
buttons.

I need a new button, like a "No thanks, I will not use this app.".

**Comment by frankyxcs** [comment]
hi kanitawana

just open consentform.html in /assets

and change "Pay for the ads-free version" to "Leave the app" or "Exit the application" 

If somebody pushes this button then the consent status is "UNKNOWN" 
so simply put finish() here in form closed: 

@Override
                    public void onConsentFormClosed(
                            ConsentStatus consentStatus, Boolean userPrefersAdFree) {
                        // Consent form was closed.
if (consentStatus.toString().equals("UNKNOWN"))   {
                            
                            finish();
                        }

  }

**Comment by rampara** [comment]
As @frankyxcs mentioned, you can edit the form HTML to meet your specific needs.
