### ISSUE TITLE
Error runtime with proguard

### ISSUE THREAD

**Issue by kimcy929** [googleads/googleads-consent-sdk-android#22]
Currently, I didn't use `implementation 'com.google.android.ads.consent:consent-library:1.0.1'` because it includes the permission `READ_PHONE_STATE` and it error bitmap when calling from.show()

I cloned and imported this lib is the module to use, it doesn't include `READ_PHONE_STATE` but it has a bug with Gson while using proguard. `Caused by: java.lang.NoSuchFieldException: UNKNOWN
`. Even I keep class or enum in the proguard file then it still makes the bug.

Thanks.

**Comment by rampara** [comment]
@kimcy929 does adding the following line to the proguard rules of your app resolve your issue?

```
-keep class com.google.ads.consent.** { <fields>; public *; }
```

**Comment by rampara** [comment]
@kimcy929 this should no longer be an issue on the latest version of this SDK (v1.0.2).
