### ISSUE TITLE
an exception error when calling requestConsentInfoUpdate()

### ISSUE THREAD

**Issue by samlu** [googleads/googleads-consent-sdk-android#24]
When I call requestConsentInfoUpdate() in UK, I got the onFailedToUpdateConsentInfo() called with the following error string.

com.google.gson.internal.LinkedTreeMap cannot be cast to com.google.ads.consent.ConsentInformation$AdNetworkLookupResponse

**Comment by samlu** [comment]
To fix this problem, should:
1. add the following statement to build.gradle (android.buildTypes.release) so proguard rules will also be included in aar file
consumerProguardFiles 'proguard-ruls.pro'

2. add the following gson related rules to proguard-ruls.pro
##---------------Begin: proguard configuration for Gson  ----------
# Gson uses generic type information stored in a class file when working with fields. Proguard
# removes such information by default, so configure it to keep all of it.
-keepattributes Signature

# For using GSON @Expose annotation
-keepattributes *Annotation*

# Gson specific classes
-dontwarn sun.misc.**

# Prevent proguard from stripping interface information from TypeAdapterFactory,
# JsonSerializer, JsonDeserializer instances (so they can be used in @JsonAdapter)
-keep class * implements com.google.gson.TypeAdapterFactory
-keep class * implements com.google.gson.JsonSerializer
-keep class * implements com.google.gson.JsonDeserializer
##---------------End: proguard configuration for Gson  ----------

**Comment by rampara** [comment]
@samlu this should no longer be an issue on that latest version of this SDK (v.1.0.2)
