### ISSUE TITLE
App requires permission WRITE_EXTERNAL_STORAGE needed

### ISSUE THREAD

**Issue by cyberdreamandroid** [googleads/googleads-consent-sdk-android#26]
When I build my apps using the consent-library 1.0.1 my AndroidManifest is extended by READ_EXTERNAL_STORAGE and WRITE_EXTERNAL_STORAGE. If I remove the dependency, no permission is added. This is reproducable. Didn't somebody test this?

Also it is not possible to localize the text. This library is a ridicolous. It is not compliant with GDPR/DSGVO to show a german user an english data policy. You could at least add the possibility by overriding text files in localized raw folders or anything else. When did Google start to develop this library, last week? It was released 5 days before GDPR/DSGVO comes into effect. So many hard working developers who need to build it by themselves now :(

**Comment by cyberdreamandroid** [comment]
Of course. But this is not how it is intended. I built a much better solution now in a few hours. Shame on Google for not supporting their developers like they should.

**Comment by frankyxcs** [comment]
yes 100 % bad for a billion dollar company :( :( :(:   

i have made my own version to of this library with more languages because time hurries
