### ISSUE TITLE
 Attempt to invoke interface method

### ISSUE THREAD

**Issue by m3toh** [googleads/googleads-consent-sdk-android#3]
Hi,
I have followed this document https://developers.google.com/admob/android/eu-consent
but got this error from onFailedToUpdateConsentInfo

> Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference

**Comment by rampara** [comment]
@m3toh this issue should be fixed by 6a6b91600f20cdeaa5ca988da04239123780b286. A new release (v1.0.1), that includes this fix was just pushed out.

**Comment by MrPat** [comment]
Can confirm 1.0.1 fixes the error for me.

**Comment by rampara** [comment]
Closing this issue as it seems to have been resolved.
