### ISSUE TITLE
bad class file magic (cafebabe) or version (0034.0000)

### ISSUE THREAD

**Issue by NmdOfficial** [googleads/googleads-consent-sdk-android#30]
I got following issue:
`Caused by: com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)`

**Comment by rampara** [comment]
@NmdOfficial are you trying to use this SDK with non-Java 8 project?

**Comment by rampara** [comment]
Closing due to non-response. Please re-open if this issue persists for you.
