### ISSUE TITLE
UNKNOWN for adfree?

### ISSUE THREAD

**Issue by DesigningKnights** [googleads/googleads-consent-sdk-android#32]
Looking through your code, it's kind of dumb to return UNKNOWN for both errors where can't determine consent, and when the user selects to prefer adfree,  Why is there not a ConsentStatus,ADFREE_PREFERRED or something similar?

**Comment by iamabhinavjain** [comment]
I think what you are looking for is **userPrefersAdFree** boolean variable inside **onConsentFormClosed** function. Value of **userPrefersAdFree** is true if user selects adfree version.

**Comment by rampara** [comment]
+1 @iamabhinavjain's comment. If the user prefers ad free, they have not consented to either personalized or non-personalized ads, which is captured by the `UNKNOWN` state.
