### ISSUE TITLE
onFailedToUpdateConsentInfo:unexpected end of stream on Connection{adservice.google.com:80, proxy=DIRECT@ hostAddress=203.208.43.121 cipherSuite=none protocol=http/1.1} (recycle count=0)

### ISSUE THREAD

**Issue by ljwan12** [googleads/googleads-consent-sdk-android#35]
onFailedToUpdateConsentInfo:unexpected end of stream on Connection{adservice.google.com:80, proxy=DIRECT@ hostAddress=203.208.43.121 cipherSuite=none protocol=http/1.1} (recycle count=0)

**Comment by rampara** [comment]
@ljwan12 are you able to consistently reproduce this error? If so, would you be able to capture a network log?

**Comment by ljwan12** [comment]
I always got this error.How to capture a network log?

**Comment by ljwan12** [comment]
1.0.3 is Okay Now
