### ISSUE TITLE
Is Google Play Instant supported?

### ISSUE THREAD

**Issue by megasoft78** [googleads/googleads-consent-sdk-android#36]
Hi,
I'm trying to use Consent SDK with Google Play Instant but I'm getting the following error:
`onFailedToUpdateConsentInfo : Cleartext HTTP traffic to adservice.google.com not permitted`

How can I solve it?

**Comment by rampara** [comment]
@megasoft78 e9565eae8ca82da44d62ed85286c4744b71f7558 should resolve this issue.

**Comment by rampara** [comment]
This issue should be resolved on v1.03 of this SDK.
