### ISSUE TITLE
 Consent form is not ready to be displayed.

### ISSUE THREAD

**Issue by GauravCreed** [googleads/googleads-consent-sdk-android#37]
Hi @dberlin 

![1](https://user-images.githubusercontent.com/13447384/40542119-5f6ca918-603c-11e8-876f-23a34a90dc44.PNG)

![2](https://user-images.githubusercontent.com/13447384/40542196-b53d4a6e-603c-11e8-8f7e-804e1e725e66.PNG)

after testing my app the response is like...

![3](https://user-images.githubusercontent.com/13447384/40542231-ef900008-603c-11e8-81e5-3d7c9ac22158.PNG)

i select less then 12 Ads Provoder in My Admob UI, also this is happening can u please help to solve this issue.????

**Comment by iordachiv** [comment]
Just call form.show in onConsentFormLoaded.

**Comment by GauravCreed** [comment]
Hi @iordachiv 

Thanks for the Quick Response

I made changes as u say, but i can't get Provider list whis is selected in My Admob UI. i send images of my response app log **(AdProviders : 0)**

**Comment by rampara** [comment]
@GauravCreed looks like you're not located in the EEA. If you're not in the EEA you will not receive a list of ad providers or be able to display the consent form. For testing, you can use the debug geography feature as described in the [developer docs](https://developers.google.com/admob/android/eu-consent#testing).

**Comment by Izzyjm** [comment]
how did you guys call form.show(); in onConsentFormLoaded ? im getting the error that "form" may have not been initialized yet ?

**Comment by sou200** [comment]
> how did you guys call form.show(); in onConsentFormLoaded ? im getting the error that "form" may have not been initialized yet ?

You have to define form variable before you initialize it.
like this:
`ConsentForm form;

form = new ConsentForm.Builder(this, privacyUrl)
                .withListener(new ConsentFormListener() {
                    @Override
                    public void onConsentFormLoaded() {
                        form.show();
                    }

                    @Override
                    public void onConsentFormOpened() {
                        // Consent form was displayed.
                    }

                    @Override
                    public void onConsentFormClosed(
                            ConsentStatus consentStatus, Boolean userPrefersAdFree) {
                        // Consent form was closed.
                    }

                    @Override
                    public void onConsentFormError(String errorDescription) {
                        Log.e("9alwa", errorDescription);
                    }
                }).build()`
