### ISSUE TITLE
Could not parse Event FE preflight response.

### ISSUE THREAD

**Issue by NmdOfficial** [googleads/googleads-consent-sdk-android#39]
What does this mean?
`Could not parse Event FE preflight response.`

**Comment by CHXAIOGE** [comment]
it probably means you publisherIDs are invalid.

**Comment by rampara** [comment]
Closing as this should no longer be an issue on the latest version of the Consent SDK.

**Comment by idanasher** [comment]
I still have this error with latest SDK.

What should I do ?

**Comment by D3vN00b** [comment]
I too have this issue with version 1.0.6, I triple checked my publisher id ... it's correct.
Tried it on 2 devices[Android 7.0, Android 8.0], got the same error.

Ads show fine with Google's test unit id & my unit id. I just can't get consent to work.

Any suggestions to try?

**Comment by PhantomLord72** [comment]
Fixed here: https://github.com/google/gson/issues/1456
