### ISSUE TITLE
request consent when offline.

### ISSUE THREAD

**Issue by randomhay** [googleads/googleads-consent-sdk-android#41]
I open app with internet. Select Personalized Ads.

I open app again without internet. The function `requestConsentInfoUpdate() `alway go to onFailedToUpdateConsentInfo(). Why it not go to `onConsentInfoUpdated()` with consent state is Personalized Ads?  

If have internet connection, it OK.

**Comment by randomhay** [comment]
But why they are using app, internet connection comeback.  Personalized display why do not have consent.

**Comment by rampara** [comment]
@randomhay requesting a consent information update requires an internet connection as a request must be made to a Google ad server. This is working as intended.
