### ISSUE TITLE
Show activity contents behind dialog

### ISSUE THREAD

**Issue by Sean343** [googleads/googleads-consent-sdk-android#46]
Is is possible to display the apps home screen behind the dialog like it does in the iOS version, rather than the outside of the dialog being completely white?

Currently when launching the app, first the apps home screen displays and them screen changes to show the dialog on a white background which can be quite jarring.

**Comment by rampara** [comment]
@Sean343 updated the Consent form to mirror the iOS version in v1.0.4 of this SDK.
