### ISSUE TITLE
Dialog backlground does not fully cover

### ISSUE THREAD

**Issue by Diranus** [googleads/googleads-consent-sdk-android#47]
On Moto G (first generation, Android 5.0.1) the white background behind the dialog does not fully cover the application. There is a gap at the upper edge (Padding for a non-existing title bar? I barely remember similar bug in one of my applications. The space has the size of the old gray non-material title bar^^).

**Comment by rampara** [comment]
@Diranus this issue should be resolved in v1.0.4 of this SDK.
