### ISSUE TITLE
Confused about ConsentInformation Api and parameters.

### ISSUE THREAD

**Issue by CHXAIOGE** [googleads/googleads-consent-sdk-android#49]
Hi, I'm quite confused about the '**requestConsentInfoUpdate**' api and how does it work. 
I have some questions below:

(1) Beacuse the request url paramters **require neither 'packagename' nor 'any deviceInfo'**, how does it work without knowing who the apps are and who is EEA user? As I know EEA should be geographically independent. So IP address may not reliable as it will not reflect to actual status. Let alone many users use proxy.

(2) I did not noticed any '**upload**' interface in ConsentInformation source code. And Response Status are stored in SharedPreference. So Does it mean the  '**requestConsentInfoUpdate**' api always returns the same result, if I use same publisherIDs?

(3) As the response use SharedPreference to save config,and not update to server(Cuz app lost data). When users uninstall and reinstall the app. EEA users may need to select the dialog again.? Or app needs a server to store users choices for convenience?

(4) For PublisherIDs, as I know one publisherID may constains multiple apps. 
Does it mean If I accept and modified the consent status, it will(or need) also apply to other apps in the same accout?

**Comment by rampara** [comment]
@CHXAIOGE user location is  determined through request ip address. The request to update consent information will return a different value if you update ad provider settings in your AdMob account or if the user travels outside the EEA. If users uninstall and reinstall the app they will be re-prompted to provide consent. Any consent provided by a user will only be stored in the shared preferences for that app.

**Comment by CHXAIOGE** [comment]
Thanks @rampara .Got it.
