### ISSUE TITLE
onFailedToUpdateConsentInfo exception

### ISSUE THREAD

**Issue by hkbb2014** [googleads/googleads-consent-sdk-android#5]
Android 8.1 nexus 5x:
onFailedToUpdateConsentInfo: 
"Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference"

What's the meaning? onConsentInfoUpdated never called. I am not in EEA. If I use genymotion, it give me onFailedToUpdateConsentInfo's errorDescription value is null.

What is the problem?

**Comment by rampara** [comment]
@hkbb2014 this issue has been fixed in the latest version of the Consent SDK (v1.0.1).
