### ISSUE TITLE
Native Dialog

### ISSUE THREAD

**Issue by elrufoelrufo** [googleads/googleads-consent-sdk-android#56]
Hello,

As @iordachiv said in https://github.com/googleads/googleads-consent-sdk-android/issues/14. 

> I think that native library/sdk should display also native dialog and not render html (with javascript and so one) instead.

Is it posible to include the consent form in native Dialog? 

Thanks. Regards.

**Comment by rampara** [comment]
@elrufoelrufo a html dialog allows there to be a common consent form between the iOS and Android SDKs. If you prefer a native form, you can implement one and manually set the consent status in the Consent SDK.
