### ISSUE TITLE
The list of EEA countries (result by consent sdk)

### ISSUE THREAD

**Issue by antonyuit** [googleads/googleads-consent-sdk-android#58]
I tested ConsentInformation.getInstance(context).isRequestLocationInEeaOrUnknown();
And with standalone google service URL "https://adservice.google.com/getconfig/pubvendors"

Austria -> true
Belgium -> true 
Bulgaria -> true 
Czech Republic -> true 
**Cyprus -> false**
Denmark -> true 
**Estonia -> false** 
Finland -> true 
France -> true 
Germany -> true 
Greece -> true 
Hungary -> true 
Iceland -> true
Ireland -> true 
Italy -> true 
Latvia -> true 
Liechtenstein -> //
Lithuania -> //
Luxembourg -> true
Malta -> //
Netherlands -> true 
Norway -> true 
Poland -> true
Portugal -> true
Romania -> true
Slovakia -> true
Slovenia -> true
Spain -> true
Sweden -> true
**United Kingdom -> false**

There are still Liechtenstein, Lithuania and Malta i couldn't test. But im still wondering the result of: Cyprus, Estonia and UK?

**Comment by CHXAIOGE** [comment]
link [https://www.eea.europa.eu/countries-and-regions](url) shows that UK,Estonia and Cyprus are EEA member countries.

**Comment by CHXAIOGE** [comment]
![eea countries](https://user-images.githubusercontent.com/18671551/40651250-cee2950e-6367-11e8-95c7-89c4431e0b5f.png)

**Comment by antonyuit** [comment]
yeah, thats the reason i have not updated consent sdk for my apps yet, i have a lot of user from UK

**Comment by rampara** [comment]
This issue tracker is for technical issues, feature requests and bug reports for the Consent SDK. For everything else, I would recommend you reach out on either the [Google Mobile Ads SDK Technical Forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk) or the [AdMob product support ](https://productforums.google.com/forum/#!forum/google-admob-help-forum).

**Comment by antonyuit** [comment]
but the problem is the consent sdk itself (ConsentInformation.getInstance(context).isRequestLocationInEeaOrUnknown() is not working correctly)
