### ISSUE TITLE
crash on android 4.2.2 API 17

### ISSUE THREAD

**Issue by MohammadAyman** [googleads/googleads-consent-sdk-android#59]
after adding  this SDK, My app didn't work on android 4.2.2 
see this image:
<img width="1009" alt="screen shot 2018-05-31 at 2 59 10 am" src="https://user-images.githubusercontent.com/20271730/40753929-1d9aea4e-647f-11e8-9f05-fe52ef661848.png">

**Comment by Cianid** [comment]
This issue is related to this one:

https://github.com/googleads/googleads-consent-sdk-android/issues/44

**Comment by rampara** [comment]
This issue should be resolved in an upcoming release. Closing as duplicate of #33.
