### ISSUE TITLE
onConsentFormError: Error: request is not in EEA or unknown

### ISSUE THREAD

**Issue by hkbb2014** [googleads/googleads-consent-sdk-android#6]
I am not in EEA. When I show the consent dialog, it give me onConsentFormError: "Error: request is not in EEA or unknown". How can I test the consent dialog outside EEA?

**Comment by rampara** [comment]
@hkbb2014 you can use the `setDebugGeography()` API addTestDevice a `DebugGeography` value of `DebugGeography.DEBUG_GEOGRAPHY_EEA`. This will only work on emulators or devices registered as test devices. To register a test device call `addTestDevice` on `ConsentInformation` with the device's hash id. The device's hash id should be output to logcat. The developer docs will be updated soon with these instructions.

**Comment by hkbb2014** [comment]
I did the following which was fine for the first install,

ConsentInformation.getInstance(this).addTestDevice("4E9**********************");
ConsentInformation.getInstance(this).setDebugGeography(DebugGeography.DEBUG_GEOGRAPHY_EEA);

boolean bInEEA = ConsentInformation.getInstance(this).isRequestLocationInEeaOrUnknown();
//bInEEA is TRUE

I open the consent dialog, and select non-personalized ads, it showed the banner correctly. Then I uninstall the app, and re-install the app.

This time bInEEA return isRequestLocationInEeaOrUnknown() return FALSE!!!

I thought the hashed device id was updated at the beginning, but I am wrong, I get the same hashed device id from logcat. Why this function can be so unstable????

**Comment by hkbb2014** [comment]
Now I am integrating another apps, it keep giving this error:

onConsentFormError: Error: request is not in EEA or unknown.

I don't know why suddenly addTestDevice and setDebugGeography stop working.

**Comment by rampara** [comment]
@hkbb2014 registered test devices should be valid for the lifetime of the app session unless `reset()` is called on `ConsentInformation`. Are you ensuring to add the test device before requesting a consent information update?

**Comment by hkbb2014** [comment]
Yes I add test devices before request consent because I create a IsInEEA function to determine if user is in EEA, and I first register test devices, then call isRequestLocationInEeaOrUnknown.

THE PROBLEM IS:

If I add the test device for the first time, isRequestLocationInEeaOrUnknown() return true
then I uninstall the app, and re-install the app, isRequestLocationInEeaOrUnknown() should return true, but it return false. 

(Why it should return true? because hashedDeviceID didn't change, I checked the logcat, the hashedDeviceID remain the same)

**Comment by hkbb2014** [comment]
I observed this multiple times, using real devices (nexus 5, 5x) and genymotion emulator (android 5,6). I don't think you guys never encounter this problem, unless you are in EEA and you don't have to use this.

**Comment by hkbb2014** [comment]
This didn't prevent me from showing consent dialog. I can still showing it, without onConsentFormError: "Error: request is not in EEA or unknown". 

But I use isRequestLocationInEeaOrUnknown() to determine if user is in EEA, if yes then show consent dialog, and isRequestLocationInEeaOrUnknown() is unstable if I used with addTestDevice, and DEBUG_GEOGRAPHY_EEA.

**Comment by michalbukacek** [comment]
Hi,
I use  isRequestLocationInEeaOrUnknown() in  
 public void onConsentInfoUpdated(ConsentStatus consentStatus)  
then I decide whether it is from the EU and whether it has a clear consentStatus and then I resolve the ad and form.

using isRequestLocationInEeaOrUnknown () before it is onConsentInfoUpdated , I think it's unstable.

**Comment by hkbb2014** [comment]
@michalbukacek I see. Thanks for your advice. I will try it.

**Comment by hkbb2014** [comment]
Should be okay now! Thanks!

**Comment by rampara** [comment]
Closing this issue as it seems to have been resolved. The value returned by `isRequestLocationInEeaOrUnknown ()` will only be updated following a request to update consent info.
