### ISSUE TITLE
What about Cordova/Phonegap/Ionic apps

### ISSUE THREAD

**Issue by d12tupac** [googleads/googleads-consent-sdk-android#63]
What about Cordova/Phonegap/Ionic application that uses Admobn how to interact with the consent sdk ??

**Comment by rampara** [comment]
@d12tupac this SDK currently only supports standard Android implementations. If the plugin you are using supports extras, you can still [forward consent to the GMA SDK](https://developers.google.com/admob/android/eu-consent#forward_consent_to_the_google_mobile_ads_sdk) after you implement collecting consent for the ad providers you use.
