### ISSUE TITLE
Ad Provider question.

### ISSUE THREAD

**Issue by malta-yamato** [googleads/googleads-consent-sdk-android#64]
Why use getNonPersonalizedAdProviders I think they don't need to be consent. I 'm confused.

-ConsentInformation.java line 412.

        } else if (hasNonPersonalizedPublisherId) {
            newAdProviderSet =
                getNonPersonalizedAdProviders(response.companies, nonPersonalizedAdProvidersIds);
        } else {
            newAdProviderSet = new HashSet<>(response.companies);
        }

**Comment by rampara** [comment]
@malta-yamato currently, the only ad provider returned in this case will be Google.

**Comment by malta-yamato** [comment]
Thank you for your comment. I think It will be fine by the only AdProvider.

**Comment by malta-yamato** [comment]
If the only consented AdProvider, we don't need to check about new AdProvider and reset status when changed. It will be more safe.
