### ISSUE TITLE
Is it OK to show non personalized ads, if there's error in showing consent form, or user refuses to make a choice?

### ISSUE THREAD

**Issue by yccheok** [googleads/googleads-consent-sdk-android#67]
I was wondering, is it OK to show non personalized ads (as default behavior), if there's error in showing consent form, or user refuses to make a choice (By pressing back button) when the consent form is shown?

```
Bundle extras = new Bundle();
extras.putString("npa", "1");

AdRequest request = new AdRequest.Builder()
        .addNetworkExtrasBundle(AdMobAdapter.class, extras)
        .build();
```

**Comment by rampara** [comment]
@yccheok as described in the [developer docs](https://developers.google.com/admob/android/eu-consent), consent is required for both personalized and non-personalized ads. As this issue tracker is only for feature requests and bug reports for this SDK, I would recommend you reach out on the [AdMob Product Support Forum](https://productforums.google.com/forum/#!forum/google-admob-help-forum) for additional information on AdMob polices.
