### ISSUE TITLE
onConsentFormError (using 12 ad tech providers)

### ISSUE THREAD

**Issue by hkbb2014** [googleads/googleads-consent-sdk-android#7]
After saved 12 ad tech providers in Admob, I am still unable to load the consent dialog.

onConsentFormError: Consent form is not ready to be displayed.
onConsentFormError: Error: consent form can be used with custom provider selection only.

Do I have to wait for some time???

**Comment by frankyxcs** [comment]
I have exactly the same problem now

**Comment by hkbb2014** [comment]
Also want to know if the selection of this 12 ad providers are only for EU users. Is that right?

**Comment by hkbb2014** [comment]
The consent dialog is working now

**Comment by rampara** [comment]
@hkbb2014 @frankyxcs changes made in your AdMob account settings can take up to an hour to propagate. Closing this issue as you seem to be receiving the expected number of ad providers now.
