### ISSUE TITLE
Question: Is it ok to prevent the user from using the app if consent is not given?

### ISSUE THREAD

**Issue by cmacdonnacha** [googleads/googleads-consent-sdk-android#97]
Hi,

I was wondering if it's ok prevent the user from using the app if consent is not given? Under GDPR you cannot punish the user for not giving consent, however, needing ad revenue surely comes under "legitimate interest".

**Comment by L4grange** [comment]
Well, if you want to degrade the app experience and lose a lot of users, then I guess it's ok.

But when they don't give consent, you don't have to disable ads, you have to disable *personalised* ads. Thus you still make ad revenue, but a little bit less, since the users are less likely to click on ads that are not aligned with their interests.

**Comment by cmacdonnacha** [comment]
I'm afraid that's actually incorrect as non-personalized ads still use cookies (specifically an advertising id) so the user still needs to consent before you can display any ads.

**Comment by rareserban** [comment]
> @rareserban Thanks. Can you reference to where that is in the official documentation? GDPR is in terms of any PPI (Personal Identifiable Information), and an advertising id is PPI.

My understanding>>>

_Reference:_ https://developers.google.com/admob/android/eu-consent 

"Under the Google EU User Consent Policy, you must make certain disclosures to your users in the European Economic Area (EEA) and obtain their consent to use cookies or other local storage, where legally required, and to use personal data (such as AdID) to serve ads."

_Cookies wise:_
https://support.google.com/admob/answer/7676680 

And this is why the consent form offers you those options: non pers/pers/ads free and one CANNOT skip this. 

Now, your Therms of use defines the conditions that apply to users if they what to use the app. And under Privacy policy there should be mention to cookies and such. If you reference AdMob it is included though.

**Comment by cmacdonnacha** [comment]
Hmm, still not clear that non personalized ads do not require consent. Thanks anyway. I'd be interested for an official answer from a member of the Google team.

**Comment by rareserban** [comment]
It does require. You mention in in terms and get it with the form. Otherwise the user is free not to use the app. Or get the paid one, if any.

**Comment by cmacdonnacha** [comment]
Ok, as @L4grange mentioned the user may not be happy to not be able to use the app if they don't consent or have to pay for it but at the end of the day we have to make money from our efforts.

**Comment by L4grange** [comment]
So, if I'm understanding correctly, what @rareserban is saying is that the users must agree to the TOS in order to use the app (which includes that AdMob uses cookies in order to serve ads), and then, if they give consent, we can show personalised ads, otherwise non-personalised, and we are covered by the app's TOS for the AdMob cookies.

**Comment by cmacdonnacha** [comment]
@L4grange Sounds good to me.

**Comment by GuanacoDevs** [comment]
I have a video [here](https://drive.google.com/open?id=16Sje6pLoZ-Toi7blpuckPBdD7Zb-Aavy) where you can see how I manage the consent permission.
- (0:05) When the user opens for the very first time the app, they get to the consent screen were I offer them 3 choices:
    1. Personalized Ads
    2. Non Personalized Ads
    3. Don't use the app.
    4. Buy the app(Could be a fourth one, but the only reason one would buy the app for the first time is that he/she already tested the app before, so for me it makes no sense to offer this at the very beginning, it might sound as a scam...)
- At this point they can either choose to get personalized ads(or non) or quit the application(0:11) and uninstall later. I show them as you can see in the screen resources that can explain them how we use ads in the app and a link to our privacy policy where they can find more detail on the ads usage. But no ad is loaded until they choose either one of the first 2.

This procedure is only related with their ads preference, therefore I don't have them accepting a `PP` nor a `TOS` but there are links that will explain them with more detail to the `PP` and/or `TOS`

Once they have chosen one over the other, they still have the chance to change the ads source whiting the app or get the ads free version(0:29) ***ADS SETTINGS/VIP*** in the menu.

And finally I built my own consent form, not using the one from the SDK.

**Comment by cmacdonnacha** [comment]
@GuanacoDevs do you think not allowing them to use the app will result in negative user experience and uninstalls?

**Comment by GuanacoDevs** [comment]
@cmacdonnacha look, the reality is that nobody likes ads, I don't like ads. But my best selling app `<60 sales` in 2 years never had a complaint with the featured ads. If you are afraid to give a bad user experience don't use ads. But you know the amount of time you have invested, maybe you won't get rich from ads, Android is famous for not having buyers like iOS.
In your position I'll put the ads if somebody complains, just rethink the placing, the frequency, I bet you invested a bit of time and maybe money, forget about what people may think unless it's constructive. 

Your are the only one that knows what's best for you.

**Comment by cmacdonnacha** [comment]
Thanks @GuanacoDevs
